## Neurolucida 360 data extraction for CA1 apical dendrites
# Author: Haley E. Speed, Ph.D.
# Date: August 9, 2017

# About:
# Fetches and collates summary data from Neurolucida360 excel files 
# that were generated by selecting all 12 analyses for one CA1 apical
# dendrite. 

# Notes:
# There is a problem referencing columns by name because of formatting.
# All columns in the original excel file are referenced by number, 
# rather than by name.

# See README.md or the blog (http://www.haleygeek.com) for more 
# detailed information



library(openxlsx)
library(dplyr)

## Function definitions

# Function to get the user input for treatment/exposure group
getGroup <- function () { 
        print("Choose the treatment group:")
        print("1. group1")
        print("2. group2")
        print("3. group3")
        print("4. group4")
        groupSelect <- readline("Your selection: ")
        return(checkGroup(groupSelect))
}

# Function to validate user input        
checkGroup <- function (groupSelect){
        switch (groupSelect,
        "1" = {group <- "group1"; return(group)},
        "2" = {group <- "group2"; return(group)},
        "3" = {group <- "group3"; return(group)},
        "4" = {group <- "group4"; return(group)},
        {getGroup()})
}


# Function to calculate spine density by branch order
getBranching <- function (sheet){
        
        spines <- c()
        thin <- c()
        stubby <- c()
        shroom <- c()
        podia <- c()
        
        for (i in sheet$Order){
                spines[i] <- as.numeric(as.character(sheet[i,17]))/
                             as.numeric(as.character(sheet[i,3])) * 10
                thin[i]   <- as.numeric(as.character(sheet[i,19]))/
                             as.numeric(as.character(sheet[i,3])) * 10
                stubby[i] <- as.numeric(as.character(sheet[i,20]))/
                             as.numeric(as.character(sheet[i,3])) * 10
                shroom[i] <- as.numeric(as.character(sheet[i,21]))/
                             as.numeric(as.character(sheet[i,3])) * 10
                podia[i]  <- as.numeric(as.character(sheet[i,22]))/
                             as.numeric(as.character(sheet[i,3])) * 10
        }
        
        return(as.data.frame(cbind(order = sheet[,1], length = sheet[,3], 
                     surfaceArea = sheet[,6], volume = sheet[,9],
                     spines = spines, thin = thin, stubby = stubby, 
                     mushroom = shroom, filopodia = podia)))
}
        
# Function to caulculate spine density by distance from soma
getDistance <- function (sheet) {
        
        # Number indicates start distance of Sholl ring
        spines.0   <- 0
        spines.150 <- 0
        spines.300 <- 0
        spines.500 <- 0
        length.0   <- 0
        length.150 <- 0
        length.300 <- 0
        length.500 <- 0
        row = 0
        
        # Caculate sums of spine number and length for each Sholl ring
        for (i in sheet[,1]) {
                
                i <- as.numeric(as.character(i))
                row <- (i+10)/10
                spines <- as.numeric(as.character(sheet[row,4]))
                length <- as.numeric(as.character(sheet[row,6]))
                
                if (i < 150 & is.na(spines) == FALSE) {
                        spines.0 <- spines.0 + spines
                        length.0 <- length.0 + length
                        
                } else if (i >= 150 & i < 300 & is.na(spines) == FALSE) {
                        spines.150 <- spines.150 + spines
                        length.150 <- length.150 + length
                        
                } else if (i >= 300 & i < 500 & is.na(spines) == FALSE) {
                        spines.300 <- spines.300 + spines
                        length.300 <- length.300 + length
                } else if (i >= 500 & is.na(spines) == FALSE) {
                        spines.500 <- spines.500 + spines
                        length.500 <- length.500 + length
                }
        }
                
        # Calculate the density of spines for each Sholl ring 
        # (spines per 10 microns)
        density.0      <- spines.0 / length.0 * 10
        density.150    <- spines.150 / length.150 * 10
        density.300    <- spines.300 / length.300 * 10
        density.500    <- spines.500 / length.500 * 10
        distance       <- c("0-149","150-299","300-499","500+")
        spineNumber    <- c(spines.0, spines.150, spines.300, spines.500)
        dendriteLength <- c(length.0, length.150, length.300, length.500)
        spineDensity   <- c(density.0, density.150, density.300, 
                               density.500)

        return(as.data.frame(cbind(distance = distance, spineNumber, 
                                   dendriteLength, spineDensity)))
}

# Function to calculate Spine density for the whole dendrite
# Spine density could have been taken from the Tree Spines-Dendrite sheet, 
# but to save on memory, it was more efficient to just calculate it here.
# Note that these are spines/10 microns, not spines/1 micron as in the 
# Tree Spines-Dendrite Worksheet.
getTotal <- function (sheet.neuron, sheet.spines, sheet.branching){
        
        # Dendrite Length
        dendrite.length <- as.numeric(as.character(sheet.neuron[3,14]))
        
        # Dendrite Surface Area
        dendrite.surface <- as.numeric(as.character(sheet.neuron[3,18]))
        
        # Dendrite Volume
        dendrite.volume <- as.numeric(as.character(sheet.neuron[3,20]))
        
        # Dendrite branches
        dendrite.branches <-as.numeric(as.character(sheet.branching[,2]))
        dendrite.branches <- sum(dendrite.branches[!is.na(dendrite.branches)])
        
        # Dendrite branch orders
        dendrite.order <- length(sheet.branching[,1])
        

        # Spine Area
        spine.area <- as.numeric(as.character(sheet.spines[,9]))
        spine.area <- mean(spine.area[!is.na(spine.area)])
        
        # Spine Volume
        spine.volume <- as.numeric(as.character(sheet.spines[,7]))
        spine.volume <- mean(spine.volume[!is.na(spine.volume)])
        
        # Spine Density
        spines <- as.numeric(as.character(sheet.neuron[3,5])) / dendrite.length * 10
        thin   <- as.numeric(as.character(sheet.neuron[3,7])) / dendrite.length * 10
        stubby <- as.numeric(as.character(sheet.neuron[3,8])) / dendrite.length * 10
        shroom <- as.numeric(as.character(sheet.neuron[3,9])) / dendrite.length * 10
        podia  <- as.numeric(as.character(sheet.neuron[3,10])) / dendrite.length * 10

        
        return (c(dendrite.length, dendrite.surface,dendrite.volume, 
                      dendrite.branches,dendrite.order, spine.area, 
                      spine.volume, spines, thin, stubby, shroom, podia))
}

# Function to write collated data to file
write.outFile <- function (outFile.data, outFile.fileName, outFile.base){
        # Check to see if the summary ouput file currently exists
        # If so, read it into a dataframe
        # Check to see if the current cell has already been entered
        # If so, overwrite the data for that cell
        # Write to the summary file
        if (file.exists(outFile.fileName)) {
                outFile.existing <- read.csv(outFile.fileName, 
                                             header=TRUE, sep =",", 
                                             stringsAsFactors = FALSE)
                outFile.keep <- filter(outFile.existing, 
                                       outFile.existing$cell != outFile.base)
                outFile.keep <- rbind(outFile.keep,outFile.data)
                write.csv(outFile.keep, outFile.fileName, row.names = FALSE)
        } else { write.csv(outFile.data, outFile.fileName, row.names = FALSE) }
        
}


## Run the script

# Get directory and file information 
inFile.dir <- readline("Enter the path to the working directory: ")
inFile.name <- readline("Enter the filename: ")
inFile.path <- paste(inFile.dir,inFile.name, sep = "\\")
inFile.group <- getGroup()

# Open the file and read the relevant sheets:
# 3 - Tree Totals-Dendrite, 5 - Neuron Summary,
# 12 - Tortuous Distance - Dendrite, 6 - Spine Details
sheet.branching <- read.xlsx(inFile.path, sheet =  3, colNames=TRUE)
sheet.neuron    <- read.xlsx(inFile.path, sheet = 5, colNames=TRUE)
sheet.distance  <- read.xlsx(inFile.path, sheet = 12, colNames = TRUE)
sheet.spines    <- read.xlsx(inFile.path, sheet = 6, colNames = TRUE)

# Summary data by branch order, distance from soma, and the entire 
# apical dendrite
branching   <- getBranching(sheet.branching)   
distance    <- getDistance(sheet.distance)         
total <- getTotal(sheet.neuron, sheet.spines, sheet.branching)


## Write data to file

# Construct the pathname based on the original file name
outFile.base         <- strsplit(inFile.name, ".xlsx")
outFile.branching    <- paste(outFile.base[1],"-by branch order.csv", sep = "")
outFile.branching    <- paste(inFile.dir,outFile.branching, sep = "\\")
outFile.distance     <- paste(outFile.base[1],"-by distance.csv", sep = "")
outFile.distance     <- paste(inFile.dir,outFile.distance, sep = "\\")
outFile.allBranching <- paste(inFile.group, "_branching.csv", sep = "")
outFile.allBranching <- paste(inFile.dir,outFile.allBranching, sep = "\\")
outFile.allDistance  <- paste(inFile.group, "_distance.csv", sep = "")
outFile.allDistance  <- paste(inFile.dir,outFile.allDistance, sep = "\\")
outFile.summary      <- paste(inFile.group, "_summary.csv", sep = "")
outFile.summary      <- paste(inFile.dir,outFile.summary, sep = "\\")

write.csv(branching,outFile.branching, row.names = FALSE)
write.csv(distance,outFile.distance, row.names = FALSE)

# Assemble data to be written to the summary table
outFile.summaryData <- as.data.frame(c(outFile.base[1], total))
colnames(outFile.summaryData) <- c("cell","dendriteLength", "dendriteSurfaceArea", 
                                "dendriteVolume", "dendriteBranches", 
                                "dendriteOrders", "spineArea", "spineVolume", 
                                "totalSpines", "thinSpines", "stubbySpines", 
                                "mushroomSpines", "filopodia")
write.outFile(outFile.summaryData, outFile.summary, outFile.base)

# Assemble data to be written to the allBranches table
outFile.branchData <- cbind(outFile.base, branching)
colnames(outFile.branchData) <- c("cell", "order", "dendriteLength", 
                                  "dendriteSurfaceArea", "dendriteVolume", 
                                  "spines", "thin", "stubby", 
                                  "mushroom", "filopodia")
write.outFile(outFile.branchData, outFile.allBranching, outFile.base)

# Assemble data to be written to the allDistance table
outFile.distanceData <- cbind(outFile.base, distance)
colnames(outFile.distanceData) <- c("cell", "distance", "dendriteLength", 
                                  "spineNumber", "spineDensity")
write.outFile(outFile.distanceData, outFile.allDistance, outFile.base)

